// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4awOE1oNXPgCQAZMgms5bXqVbT-n_kOA',
    appId: '1:300735211217:web:5d37a5b2986c63a8e2c7f0',
    messagingSenderId: '300735211217',
    projectId: 'in-and-ex-2b8d0',
    authDomain: 'in-and-ex-2b8d0.firebaseapp.com',
    storageBucket: 'in-and-ex-2b8d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgrvt1Q2MDdxX-IkoZs64SMm_mAx4Vyc',
    appId: '1:300735211217:android:53fd11cbceee4fd0e2c7f0',
    messagingSenderId: '300735211217',
    projectId: 'in-and-ex-2b8d0',
    storageBucket: 'in-and-ex-2b8d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiIQyqQTgAXclUuRVdwyPNjHji045MYtA',
    appId: '1:300735211217:ios:c1682b11c5b5d85ee2c7f0',
    messagingSenderId: '300735211217',
    projectId: 'in-and-ex-2b8d0',
    storageBucket: 'in-and-ex-2b8d0.appspot.com',
    iosBundleId: 'com.example.inAndEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiIQyqQTgAXclUuRVdwyPNjHji045MYtA',
    appId: '1:300735211217:ios:c1682b11c5b5d85ee2c7f0',
    messagingSenderId: '300735211217',
    projectId: 'in-and-ex-2b8d0',
    storageBucket: 'in-and-ex-2b8d0.appspot.com',
    iosBundleId: 'com.example.inAndEx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4awOE1oNXPgCQAZMgms5bXqVbT-n_kOA',
    appId: '1:300735211217:web:9a39acd2240964fce2c7f0',
    messagingSenderId: '300735211217',
    projectId: 'in-and-ex-2b8d0',
    authDomain: 'in-and-ex-2b8d0.firebaseapp.com',
    storageBucket: 'in-and-ex-2b8d0.appspot.com',
  );
}
